[package]
name = "christina"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
arboard = "2.1.1"
image = "0.24.2"
notify-rust = "4.5.8"
screenshots = "0.1.1"
tesseract = "0.12.0"
time = { version = "0.3.9", features = ["formatting", "local-offset"] }
